# Explicitly export ResearchState for import
__all__ = ["ResearchState"]
# src/graph/state.py
from typing import TypedDict, List, Optional, Dict, Any

class AgentSourceResult(TypedDict, total=False):
    """Represents raw output from a single tool call."""
    name: str
    items: List[Any]
    metadata: Dict[str, Any]

class AgentResult(TypedDict, total=False):
    """Collects raw results and metadata for an agent."""
    sources: List[AgentSourceResult]
    elapsed: float
    tokens: int
    cost: float
    details: Dict[str, Any]

class ResearchState(TypedDict, total=False):
    """
    Represents the state of our research graph using raw agent data.
    """
    topic: str                      # The initial user input
    mode: str                       # Research depth selector
    research_plan: Optional[str]    # The plan generated by the orchestrator
    web_results: Optional[AgentResult]  # Raw data from web research tools
    academic_results: Optional[AgentResult]  # Raw data from academic sources
    news_results: Optional[AgentResult]  # Raw data from news sources
    social_sentiment: Optional[AgentResult]  # Raw social sentiment data
    financial_data: Optional[AgentResult]    # Raw financial data
    perplexity_results: Optional[AgentResult]  # Mock Perplexity research data
    youtube_results: Optional[AgentResult]    # Mock YouTube research data
    vector_store_result: Optional[AgentResult]  # Vector store status
    rag_result: Optional[AgentResult]          # RAG retrieval output
    cleanup_result: Optional[AgentResult]      # Cleanup agent output
    synthesizer_result: Optional[AgentResult]  # Metrics from the synthesizer agent
    final_report: Optional[str]     # The final compiled report
    archive_path: Optional[str]    # Path to archived JSON snapshot


